on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - name: Check that no non-test files import Ginkgo or Gomega
        run: .github/workflows/no_ginkgo.sh
      - name: Check that go.mod is tidied
        run: |
          cp go.mod go.mod.orig
          cp go.sum go.sum.orig
          go mod tidy
          diff go.mod go.mod.orig
          diff go.sum go.sum.orig
      - name: staticcheck
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
